In [1]:
import pandas as pd
import plotly.express as px

df = pd.DataFrame({
    "group": (
        ["A"] * 12
        + ["B"] * 12
        + ["C"] * 12
    ),
    "score": [
        # A 그룹
        52, 55, 58, 60, 61, 63,
        65, 67, 68, 70, 72, 95,

        # B 그룹
        48, 50, 53, 54, 56, 57,
        58, 60, 62, 64, 66, 68,

        # C 그룹
        60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82,
    ],
})

print(df)

   group  score
0      A     52
1      A     55
2      A     58
3      A     60
4      A     61
5      A     63
6      A     65
7      A     67
8      A     68
9      A     70
10     A     72
11     A     95
12     B     48
13     B     50
14     B     53
15     B     54
16     B     56
17     B     57
18     B     58
19     B     60
20     B     62
21     B     64
22     B     66
23     B     68
24     C     60
25     C     62
26     C     64
27     C     66
28     C     68
29     C     70
30     C     72
31     C     74
32     C     76
33     C     78
34     C     80
35     C     82

In [2]:
df.groupby('group')['score'].describe()

       count  mean        std   min    25%   50%   75%   max
group
A       12.0  65.5  11.065918  52.0  59.50  64.0  68.5  95.0
B       12.0  58.0   6.252272  48.0  53.75  57.5  62.5  68.0
C       12.0  71.0   7.211103  60.0  65.50  71.0  76.5  82.0

In [3]:
fig = px.histogram(
    df,
    x='score',
    y='group',
)

fig.show()

In [5]:
px.histogram(
    df,
    x='score',
    nbins=5,
)

In [6]:
df['group'].value_counts()

group
A    12
B    12
C    12
Name: count, dtype: int64

In [12]:
fig = px.histogram(
    df,
    x='score',
    color='group',
    opacity=0.6,
    # barmode='overlay'
)

fig.show()

In [13]:
fig = px.histogram(
    df, # 데이터
    x='score', # X축
    color='group',  # 그룹핑(색상으로 구분)
    opacity=0.6, # 투명도
    barmode='overlay' # 막대기 유형
)

fig.show()

In [14]:
# A그룹에 대한 상자수염그래프를 그리시오
group_a = df[df['group'] == 'A']

group_a

   group  score
0      A     52
1      A     55
2      A     58
3      A     60
4      A     61
5      A     63
6      A     65
7      A     67
8      A     68
9      A     70
10     A     72
11     A     95

In [16]:
fig = px.box(
    group_a,
    y='score',
    title='A그룹 점수별 분포'
)

fig.show()

In [17]:
fig = px.box(
    df,
    x='group',
    y='score',
)

fig.show()

In [18]:
fig = px.box(
    df,
    x='group',
    y='score',
    color='group',
)

fig.show()

In [19]:
fig = px.violin(
    group_a,
    y='score',
)

fig.show()

In [20]:
fig = px.violin(
    group_a,
    y='score',
    points='all',
)

fig.show()

In [22]:
fig = px.violin(
    df,
    x='group',
    y='score',
    color='group',
    points='all',
    title='그룹별 점수 밀도'
)

fig.show()